version: '2'
services:
    nginx:
        image: nginx:1.14
        container_name: coaster_cloud_report_nginx
        ports:
            - 8030:80
        volumes:
            - ./docker/nginx/server.conf:/etc/nginx/conf.d/app.conf:delegated
        networks:
            - local
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
            target: php-base
        container_name: coaster_cloud_report_php
        env_file:
            - .env
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - local
networks:
    local:
        driver: bridge
