version: '2'
services:
    nginx:
        image: nginx:1.14
        container_name: coaster_cloud_report_nginx
        ports:
            - 80:80
        volumes_from:
            - php
        networks:
            - local
    php:
        image: migoapps/docker-php:3.0.1
        container_name: coaster_cloud_report_php
        env_file:
            - .env
        volumes:
            - ./:/var/www/html:delegated
            - ./docker/nginx/server.conf:/etc/nginx/conf.d/app.conf:delegated
        networks:
            - local
networks:
    local:
        driver: bridge
