version: '2'
services:
    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
            target: base
        container_name: coaster_cloud_media_nginx
        ports:
            - 8030:80
        volumes:
            - ./docker/nginx/server.conf:/etc/nginx/conf.d/app.conf:delegated
        networks:
            - local
        depends_on:
          - php
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
            target: base
        container_name: coaster_cloud_media_php
        env_file:
            - .env
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - local
networks:
    local:
        driver: bridge
