version: '3.8'
services:
    nginx:
        build:
            context: ./
            dockerfile: ./docker/nginx/Dockerfile
        container_name: coaster_cloud_media_service_nginx
        ports:
            - 80:8030
        volumes:
            - ./docker/nginx/server.conf:/etc/nginx/conf.d/server.conf:delegated
        networks:
            - local
        depends_on:
          - php
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: coaster_cloud_media_service_php
        env_file:
            - .env
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - local
networks:
    local:
        driver: bridge
