version: '3.8'
services:
    nginx:
        image: ghcr.io/coaster-cloud/media-service-nginx:latest
        container_name: coaster_cloud_media_service_nginx
        restart: always
        ports:
            - 8030:8030
        networks:
            - local
        depends_on:
          - php
    php:
        image: ghcr.io/coaster-cloud/media-service-php:latest
        container_name: coaster_cloud_media_service_php
        restart: always
        env_file:
            - .env
        networks:
            - local
networks:
    local:
        driver: bridge
