# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $banners: !tagged_iterator { tag: 'app.banner', index_by: 'key', default_index_method: 'getKey' }
            $assets: '%kernel.project_dir%/assets/'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Action\:
        resource: '../src/Action/'
        tags: ['controller.service_arguments']

    _instanceof:
        App\Banner\BannerInterface:
            tags: [app.banner]
