name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push nginx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/nginx/Dockerfile
          push: true
          tags: |
            ghcr.io/coaster-cloud/media-service-nginx:latest

      - name: Build and push php
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/php/Dockerfile
          push: true
          build-args: |
            bootstrap=production
          tags: |
            ghcr.io/coaster-cloud/media-service-php:latest
